### ISSUE TITLE
Re-release Gem and Bump Version

### ISSUE THREAD

**Issue by garethrees** [thoughtbot/fistface#3]
A few months ago I submitted [this patch](https://github.com/thoughtbot/fistface/pull/2) but the gem available on [rubygems](http://rubygems.org/gems/fistface) is still the previous version.

Could you re-release the gem with the current code?

Thanks

**Comment by croaky** [comment]
Absolutely. Done. Released 1.0.1. Thanks for the nudge, Gareth.
